### ISSUE TITLE
Check for hidden and system files in curations

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/Curation-Validation-Bot#26]
Curations should never include hidden or system files such as `desktop.ini` or `Thumbs.db`. The bot should flag curations that have these files. Checking by filename is an OK approach, but I think it would be best to check for any files with the system (S) or hidden (H) attributes.
https://www.2brightsparks.com/resources/articles/understanding-file-attributes.html

**Comment by curation-bot-guy** [comment]
Already implemented.
